#!/usr/bin/env php
<?php
require __DIR__.'/vendor/autoload.php';

//TODO: fix namespace to fit with other nand2tetris software
use TaHUoP\App;
use TaHUoP\Parser;

(new App(new Parser()))
    ->run();
